# Generated by Django 2.1.5 on 2019-01-31 14:58

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GomokuRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_record', models.TextField()),
                ('game_date', models.DateTimeField()),
                ('result', models.IntegerField()),
                ('swap', models.BooleanField()),
                ('swap_2', models.BooleanField()),
                ('color_change', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GomokuRecordFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_record_file', models.FileField(null=True, upload_to=core.models.gomoku_record_image_file_path)),
                ('file_path', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('win', models.IntegerField()),
                ('loss', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to=core.models.profile_image_file_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gomokurecord',
            name='black_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_player', to='core.Player'),
        ),
        migrations.AddField(
            model_name='gomokurecord',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
        migrations.AddField(
            model_name='gomokurecord',
            name='white_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to='core.Player'),
        ),
    ]
