# Generated by Django 2.1.5 on 2019-01-31 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GomokuRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(max_length=255)),
                ('game_date', models.DateTimeField()),
                ('result', models.IntegerField()),
                ('swap', models.BooleanField()),
                ('swap_2', models.BooleanField()),
                ('color_change', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('win', models.IntegerField()),
                ('loss', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='gomokurecord',
            name='black_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_player', to='core.Player'),
        ),
        migrations.AddField(
            model_name='gomokurecord',
            name='white_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to='core.Player'),
        ),
    ]
