# Generated by Django 2.1.5 on 2019-01-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_gomokurecordfile_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='loss',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='win',
            field=models.IntegerField(blank=True),
        ),
    ]
