# Generated by Django 2.1.5 on 2019-03-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190202_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default='adam', max_length=250),
            preserve_default=False,
        ),
    ]
