# Generated by Django 2.1.5 on 2019-01-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190131_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='loss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='win',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
