# Generated by Django 2.1.5 on 2019-03-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190301_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='gomokurecordfile',
            name='status',
            field=models.CharField(default='file', max_length=50),
            preserve_default=False,
        ),
    ]
