# Generated by Django 2.1.5 on 2019-02-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190201_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gomokurecord',
            name='result',
            field=models.CharField(max_length=50),
        ),
    ]
