# Generated by Django 2.1.5 on 2019-03-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190302_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gomokurecord',
            options={'ordering': ('-created', 'game_date')},
        ),
    ]
