# Generated by Django 2.1.5 on 2019-03-04 14:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190302_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 4, 14, 2, 48, 130309, tzinfo=utc)),
        ),
    ]
