# Generated by Django 2.1.5 on 2019-03-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190307_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gomokurecordfile',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
