# Generated by Django 2.1.5 on 2019-03-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0004_userprofile_slug")]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="slug",
            field=models.SlugField(max_length=250, unique=True),
        )
    ]
