# Generated by Django 2.1.5 on 2019-03-01 12:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0007_gomokurecordfile_url")]

    operations = [
        migrations.AlterField(
            model_name="gomokurecordfile",
            name="game_record_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=core.models.gomoku_record_image_file_path,
            ),
        ),
        migrations.AlterField(
            model_name="gomokurecordfile",
            name="url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
