# Generated by Django 2.1.5 on 2019-03-02 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("core", "0008_auto_20190301_1245")]

    operations = [
        migrations.AlterModelOptions(
            name="gomokurecord", options={"ordering": ("-created",)}
        ),
        migrations.AddField(
            model_name="gomokurecord",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
