# Generated by Django 2.1.5 on 2019-03-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0012_auto_20190304_1403")]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="slug",
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
