# Generated by Django 2.1.5 on 2019-03-07 13:10

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0013_auto_20190304_1411")]

    operations = [
        migrations.AlterField(
            model_name="gomokurecordfile",
            name="game_record_file",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to=core.models.gomoku_record_image_file_path,
            ),
        ),
        migrations.AlterField(
            model_name="gomokurecordfile",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="gomokurecordfile",
            name="url",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
